index = "README.md"

[[get]]
uri="team"
file="team2.md"

[[get]]
uri="externals"
file="externals.md"

[[get]]
uri="events"
file="events.md"

[[get]]
uri="publications"
file="publications.md"

[[get]]
uri="preprints"
file="preprints.md"
